version: '3.4'

services:

  vehicles:
    image: finemanagerapp.vehicles:latest
    build:
      context: ./src/Microservices/Vehicles
      dockerfile: Dockerfile
      args:
        - configuration=Debug
    ports:
      - 80:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    entrypoint: ["dotnet", "Vehicles.dll"]


  finemanager:
    image: finemanagerapp.finemanager:latest
    build:
      context: ./src/Microservices/FineManager
      dockerfile: Dockerfile
      args:
        - configuration=Debug
    ports:
      - 81:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    entrypoint: ["dotnet", "FineManager.dll"]


  trafficevents:
    image: finemanagerapp.trafficevents:latest
    build:
      context: ./src/Microservices/TrafficEvents
      dockerfile: Dockerfile
      args:
        - configuration=Debug
    ports:
      - 82:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    entrypoint: ["dotnet", "TrafficEvents.dll"]


  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80


