on: workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  build-deploy-images:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: azure/login@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'

    - name: 'Deploy Bicep templates'
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: 'finemanagerapp'
        template: deploy/bicep/main.bicep
        parameters: 'registryUser=${{ secrets.AZURE_ACR_PRINCIPAL }} registryPass=${{ secrets.AZURE_ACR_PRINCIPAL_PASSWORD }}'
        failOnStdErr: true



